### ISSUE TITLE
Elaboration fails when PIPE_REG=0

### ISSUE THREAD

**Issue by polyee13** [mcjtag/bitonic_sorter#2]
Able to compile and sim with PIPE_REG=1 but with it set to 0

Error-[V2KGEUV] Unknown or bad value for genvar
../../rtl/bitonic_sort_median_filter/bitonic_comp.v, 80
  Instance/Generate block name: 
  tb_bitonic_sort_median_filter.inst_bitonic_sort_median_filter_adc.inst_bitonic_sort.SORT_STAGE[0].BLOCK[0].bitonic_block_inst.BLOCK_STAGE[0].NODE[0].bitonic_node_inst.COMP[0].comp_inst
  Elaboration time unknown or bad value encountered for generate if-statement 
  condition expression.
  Please make sure it is elaboration time constant.

1 error
CPU time: .131 seconds to compile

 common elaboration failed
Command exited with non-zero status 255
        0:01.04 real,   0.58 user,      0.63 sys

Steps to reproduce:
1) Set PIPE_REG - 0
2) run sim  (we are using Synopsys U-2023.03)

I have not tried any other simulator

**Comment by mcjtag** [comment]
PIPE_REG = 0 is illegal

**Comment by mcjtag** [comment]
Actually, iI think it could be better if PIPE_REG = 0 (for no registers/triggers in pipeline). Done. I`ve tried it in Vivado & Cadence.
